displayName: Shorty
summary: A simple Link Shortener for traefik  
type: middleware
import: github.com/spakl-io/shorty
# compatibility: v2.10
testData:
  links:
    test1: https://google.com
    test2: https://google.com