version: '3.2'

# networks:
  # proxy:
  #   driver: bridge
  #   name: proxy
  #   attachable: true
  #   ipam:
  #     config:
  #       - subnet: 192.160.0.0/24
  #         gateway: 192.160.0.1
networks:
  proxy:
    external: true




volumes:
  tls-certs:


services:
  traefik:
    image: traefik:v2.10.7
    container_name: "traefik"
    restart: unless-stopped
    hostname: "traefik"
    # so you can add portainer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      # - "80:80"
      - "443:443"
      - 8083:8083
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./:/plugins-local/src/gitlab.com/spakl/shorty"
      - "tls-certs:/certs"
    environment:
      - CF_API_EMAIL
      - CF_DNS_API_TOKEN
    command:
      - --api
      - --api.dashboard
      # - --certificatesresolvers.cloudflare
      # - --certificatesresolvers.cloudflare.acme.dnschallenge
      # - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      # - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53
      # - --certificatesresolvers.cloudflare.acme.storage=certs/acme.json

      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --serverstransport.insecureskipverify
      - --entryPoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.forwardedheaders.insecure
      - --entrypoints.websecure.http.tls
      - --entryPoints.private.address=:8083
      - --ping=true
      - --ping.entryPoint=private
      
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=proxy

      - --metrics.prometheus
      - --metrics.prometheus.addentrypointslabels
      - --metrics.prometheus.addrouterslabels
      - --metrics.prometheus.addserviceslabels
      - --metrics.prometheus.manualrouting=true
      - --metrics.prometheus.entrypoint=private

      # - --log.format=JSON
      - --log.level=DEBUG
      # - --accesslog
      # - --tracing=false
      # - --tracing.serviceName=zsvc.treafik
      # - --tracing.jaeger
      # - --tracing.jaeger.collector.endpoint=https://otel.ops.spakl.io/v1/traces
      # - --experimental.localplugins.shorty.moduleName=gitlab.com/spakl/shorty
      - --experimental.plugins.shorty.moduleName=github.com/Spakl-io/shorty
      - --experimental.plugins.shorty.version=v0.0.1
      # - --experimental.plugins.shorty.version=latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      # - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      # - "traefik.http.routers.traefik.tls.domains[0].main=zsvc.spakl.io"
      # - "traefik.http.routers.traefik.tls.domains[0].sans=*.zsvc.spakl.io"

      
      - "traefik.http.routers.shorty.rule=Host(`shorty.localhost`)"
      - "traefik.http.routers.shorty.service=traefik-shorty@docker"
      - "traefik.http.routers.shorty.middlewares=my-shorty@docker"
      - "traefik.http.middlewares.my-shorty.plugin.shorty.links.proxmox=https://proxmox.ops.spakl.io"
      - "traefik.http.middlewares.my-shorty.plugin.shorty.links.proxmox2=https://proxmox.ops.spakl.io"
      - "traefik.http.middlewares.my-shorty.plugin.shorty.links.proxmox2=https://ops.spakl.io"
      - "traefik.http.middlewares.my-shorty.plugin.shorty.links.google=https://google.com"

    # depends_on:
      # - traefik_certs_init


  # traefik_certs_init:
    # image: alpine:latest
    # container_name: "traefik_certs_init"
    # hostname: "traefik_certs_init"
    # networks:
      # - proxy
    # volumes:
      # - "tls-certs:/certs"
    # command:
      # - sh
      # - -c
      # - |
        # mkdir -p /certs &&
        # touch /certs/acme.json &&
        # chmod 600 /certs/acme.json