apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: orty-sh-letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: robot@email.io ## USE YOUR DOMAIN EMAIL
    privateKeySecretRef:
      name: orty-sh-letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: robot@email.io ## USE YOUR DOMAIN EMAIL
            apiTokenSecretRef:
              name: orty-sh-cloudflare-token-secret
              key: token
        selector:
          dnsZones:
            - "orty.sh" ## USE YOUR DOMAIN NAME