apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orty-sh
  namespace: shorty
spec:
  secretName: orty-sh-tls
  issuerRef:
    name: orty-sh-letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.orty.sh"   ## USE YOUR DOMAIN NAME
  dnsNames:
  - "orty.sh"               ## USE YOUR DOMAIN NAME
  - "*.orty.sh"             ## USE YOUR DOMAIN NAME